repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
